CREATE TABLE bathrooms (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    bathroom_user_id VARCHAR(30)
        REFERENCES accounts(user_identifier) ON DELETE CASCADE NOT NULL,
    bathroom_user_name VARCHAR(20)
        REFERENCES accounts("user_name") ON DELETE CASCADE NOT NULL,
    "name" TEXT NOT NULL,
    longitude NUMERIC NOT NULL,
    latitude NUMERIC NOT NULL,
    handi BOOLEAN,
    men BOOLEAN,
    women BOOLEAN,
    unisex BOOLEAN,
    family BOOLEAN,
    modified TIMESTAMP NOT NULL DEFAULT now()
);