CREATE TABLE reviews (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  bathroom_id INTEGER
    REFERENCES bathrooms(id) ON DELETE CASCADE NOT NULL,
  review_user_id VARCHAR(30)
    REFERENCES accounts(user_identifier) ON DELETE CASCADE NOT NULL,
  review_user_name VARCHAR(20)
    REFERENCES accounts("user_name") ON DELETE CASCADE NOT NULL,
  modified TIMESTAMP NOT NULL DEFAULT now(),
  sex TEXT,
  clean INTEGER NOT NULL,
  privacy INTEGER NOT NULL,
  accessibility INTEGER,
  handSoap INTEGER,
  handDryer INTEGER,
  smell INTEGER NOT NULL,
  comment TEXT,
  direction TEXT,
  overall_score NUMERIC NOT NULL
);
